version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/dev.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
      - backend-network
    restart: always
  client:
    build:
      context: .
      dockerfile: ./apps/client/dev.Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    restart: always
  db:
    image: postgres:16-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: local
    networks:
      - database-network
      - backend-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - database-network

networks:
  app-network:
  backend-network:
  database-network:
