version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/dev.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
      - backend-network
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: api
      POSTGRES_PASSWORD: development
      POSTGRES_DATABASE: app
      NODE_ENV: DEV
    restart: always
  client:
    build:
      context: .
      dockerfile: ./apps/client/dev.Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    restart: always
  db:
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_PASSWORD: local
      API_PASSWORD: development
    networks:
      - database-network
      - backend-network
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - database-network

networks:
  app-network:
  backend-network:
  database-network:
