version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/dev.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always
  client:
    build:
      context: .
      dockerfile: ./apps/client/dev.Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    restart: always

networks:
  app-network:
